### ISSUE TITLE
can't write to csv - TypeError: Invalid data...

### ISSUE THREAD

**Issue by naxmefy** [C2FO/fast-csv#154]
my example

``` JavaScript
'use strict';

const fs = require('fs');
const path = require('path');
const csv = require('fast-csv');

const csvWriter = csv
    .createWriteStream({headers: true})
    .pipe(fs.createWriteStream(path.resolve(__dirname, 't.csv')));

csvWriter.write({a: "1", b: "2"});
csvWriter.write({a: "1", b: "2"});
csvWriter.write({a: "1", b: "2"});
csvWriter.end();
```

got following errors

```
TypeError: Invalid non-string/buffer chunk
    at validChunk (_stream_writable.js:189:10)
    at WriteStream.Writable.write (_stream_writable.js:218:12)
    ...
```

Sry dont understand the problem - if i use a piped solution all fine
from read to write works - but not write?!?!?!?!

**Comment by bsautron** [comment]
Hi @naxmefy,

Its because the `.pipe` function return the current stream (the stream pass on parameters). So your `csvWriter` is your `t.csv` write stream, not you real csv stream.

Try to separate them:

```js
const csvWriter = csv.createWriteStream({headers: true});

csvWriter.pipe(fs.createWriteStream(path.resolve(__dirname, 't.csv')));
```

**Comment by naxmefy** [comment]
i see thanks
