### ISSUE TITLE
Error: Parse Error: expected: '"' got: 'y'. at 'you got my

### ISSUE THREAD

**Issue by loretoparisi** [C2FO/fast-csv#186]
```
 [Tue May 02 2017 18:52:04 GMT+0200 (CEST)] merge error:
Error: Parse Error: expected: '"' got: 'y'. at 'you got my
    at parseEscapedItem (/node_modules/fast-csv/lib/parser/parser.js:80:19)
    at ParserStream.parseLine [as parser] (/node_modules/fast-csv/lib/parser/parser.js:192:30)
    at ParserStream._parseLine [as _parse] (/node_modules/fast-csv/lib/parser/parser_stream.js:178:25)
    at ParserStream._transform (/node_modules/fast-csv/lib/parser/parser_stream.js:221:18)
    at ParserStream.Transform._read (_stream_transform.js:167:10)
    at ParserStream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:334:12)
    at clearBuffer (_stream_writable.js:441:7)
    at onwrite (_stream_writable.js:373:7)
    at WritableState.onwrite (_stream_writable.js:90:5)
```

The problem is that this file was generated by `FastCSV` itself, so it should be valid.

My csv options for reading and writing are:

```
{
                // first row is cols header
                headers: false
                // delimiter
                , delimiter: '\t'
                // character to use to escape values that contain a delimiter. If you set to null then all quoting will be ignored
                //, quote: '"'
                // The character to use when escaping a value that is quoted and contains a quote character
                , escape: '\\'
                // ignore empty rows
                , ignoreEmpty: true
                // discard columns that do not map to a header.
                , discardUnmappedColumns: true
                // consider empty lines with too few fields as error
                , strictColumnHandling: false 
            }
```

This is how I normalize the input text

```
        text=text.toLowerCase();
        text=text.replace(/(?:\\[rn]|[\r\n]+)+/g, " ");
        text=text.replace(/'/g, " ");
        text=text.replace(/"/g, '');
        text=text.replace(/\./g, ' \. ');
        text=text.replace(/,/g, ' \, ');
        text=text.replace(/\(/g, ' ( ');
        text=text.replace(/\)/g, ' ) ');
        text=text.replace(/!/g, ' ! ');
        text=text.replace(/\?/g, ' ! ');
        text=text.replace(/;/g, ' ');
        text=text.replace(/:/g, ' ');
        text=text.replace(/\t+/g,'\t').replace(/\t\s/g,' ').replace(/\t/g,' ');
```

**Comment by loretoparisi** [comment]
**[UPDATE]**

The only way I have found to fix this was using `sed`

```
normalize_text() {
  tr '[:upper:]' '[:lower:]' | \
    sed -e "s/'/ ' /g" -e 's/"//g' -e 's/\./ \. /g' -e 's/<br \/>/ /g' \
        -e 's/,/ , /g' -e 's/(/ ( /g' -e 's/)/ ) /g' -e 's/\!/ \! /g' \
        -e 's/\?/ \? /g' -e 's/\;/ /g' -e 's/\:/ /g' | tr -s " "
}
cat $1 | normalize_text > $2
```

I've tried to replicated the regex in javascript but with no success:

```
text=text.toLowerCase();
        text=text.replace(/(?:\\[rn]|[\r\n]+)+/g, " ");
        text=text.replace(/'/g, " ");
        text=text.replace(/"/g, '');
        text=text.replace(/\./g, ' \. ');
        text=text.replace(/,/g, ' \, ');
        text=text.replace(/\(/g, ' ( ');
        text=text.replace(/\)/g, ' ) ');
        text=text.replace(/!/g, ' ! ');
        text=text.replace(/\?/g, ' ! ');
        text=text.replace(/;/g, ' ');
        text=text.replace(/:/g, ' ');
        text=text.replace(/\t+/g,'\t').replace(/\t\s/g,' ').replace(/\t/g,' ');
```

That should cover the `sed` regular expressions, but it seems it does not work in the same way.

**Comment by doug-martin** [comment]
Doing some house cleaning. Reopen if you have further questions
