### ISSUE TITLE
Test fails on Node 8

### ISSUE THREAD

**Issue by kibertoad** [C2FO/fast-csv#207]
Node.js 8.9.3, Windows 10.

If I just run "npm install" and try running "npm test", it fails due to not finding grunt. No biggie, I run "npm install grunt-cli" and repeat.

```
Running "jshint:file" (jshint) task
Warning: Path must be a string. Received null Use --force to continue.
```

OK, I update grunt-contrib-jshint to "^1.1.0", suspecting that current version is incompatible with new npm and/or Node.js. That seems to help, I get to tests actually executing, and then:

```
C:\sources2\fast-csv\fast-csv\test\issues.test.js:156
                    throw err;
                    ^

AssertionError [ERR_ASSERTION]: [ { first_name: 'First\r\n1',
    last_name: 'Last\r\n1',
    email_address: 'email1@email.com',
    address: '1 Street St,\r\nS deepEqual [ { first_name: 'First\n1',
    last_name: 'Last\n1',
    email_address: 'email1@email.com',
    address: '1 Street St,\nState S
    at ParserStream.<anonymous> (C:\sources2\fast-csv\fast-csv\test\parsing.test.js:1304:24)
    at emitOne (events.js:121:20)
    at ParserStream.emit (events.js:211:7)
    at spreadArgs (C:\sources2\fast-csv\fast-csv\lib\extended.js:43:25)
    at ParserStream.emit (C:\sources2\fast-csv\fast-csv\lib\parser\parser_stream.js:314:17)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

I presume something is drastically different in error handling between Node.js 5 and Node.js 8, but I am afraid I'm not familiar enough with what exactly test is trying to achieve to provide fix myself.

**Comment by doug-martin** [comment]
This is fixed with the latest version, the new version is compatible with version `>=8`
