### ISSUE TITLE
Error: stream.push() after EOF

### ISSUE THREAD

**Issue by cggaurav** [C2FO/fast-csv#225]
Reading a ~500MB CSV file via stream.

```
Error: stream.push() after EOF
    at readableAddChunk (_stream_readable.js:240:30)
    at PassThrough.Readable.push (_stream_readable.js:208:10)
    at PassThrough.Transform.push (_stream_transform.js:147:32)
    at readStream.on.on.pipe.pipe.eventStream.map (/Users/project-x/csv.js:74:28)
    at wrappedMapper (/Users/project-x/node_modules/map-stream/index.js:84:19)
```

**Comment by cggaurav** [comment]
I tried the same file with npms `csv-parser` and did not face an issue for the same encoding `utf-8`

**Comment by doug-martin** [comment]
Try this with the latest version, a lot of the streaming issues have been resolved with the new version. 

Closing for now create a new issue with an example dataset and code for parsing if this is still a problem
