### ISSUE TITLE
Error when parsing csv file with double quotes inside (comma as delimiter)

### ISSUE THREAD

**Issue by yao23** [C2FO/fast-csv#51]
How to handle the exception with the invalid csv file like double quotes in the content?

I want to keep double quotes finally or catching the exception and ignoring the invalid row is acceptable as well, like the following example, I want first column as <pre>blah...Start by "stamping" powder on the outer edges of face and ...blah</pre>

For example, the "stamping" in the csv file:

<pre>
"blah...Start by "stamping" powder on the outer edges of face and ...blah","blah","blah blah","blah blah blah"
</pre>

Error:

<pre>
error: Parse Error: expected: '"' got: 's'. at 'stamping"  Error: Parse Error: expected: '"' got: 's'. at 'stamping"
    at parseEscapedItem (/node_modules/fast-csv/lib/parser.js:73:19)
    at ParserStream.parseLine [as parser] (/node_modules/fast-csv/lib/parser.js:142:30)
    at ParserStream._parseLine [as _parse] (/node_modules/fast-csv/lib/parser_stream.js:109:25)
    at ParserStream.extended.extend._transform (/node_modules/fast-csv/lib/parser_stream.js:166:29)
    at ParserStream.Transform._read (_stream_transform.js:179:10)
    at ParserStream.Transform._write (_stream_transform.js:167:12)
    at doWrite (_stream_writable.js:221:10)
    at writeOrBuffer (_stream_writable.js:211:5)
    at ParserStream.Writable.write (_stream_writable.js:180:11)
    at write (_stream_readable.js:583:24) 
</pre>

the error message follows the above one

<pre>
verbose: Shutting down Aura...
verbose: Closing Http Server
error: Error: undefined
    at Object.serverErrorOccurred [as 500] (/config/500.js:19:28)
    at ServerResponse.respond500 [as serverError] (/node_modules/aura/lib/aura/http/hooks/request.js:127:23)
    at Domain.<anonymous> (/node_modules/aura/lib/aura/express/load.js:56:17)
    at Domain.EventEmitter.emit (events.js:95:17)
    at ParserStream.EventEmitter.emit (events.js:70:21)
    at spreadArgs (/node_modules/fast-csv/lib/parser_stream.js:20:21)
    at ParserStream.extended.extend.emit (/node_modules/fast-csv/lib/parser_stream.js:217:13)
    at ParserStream.onerror (_stream_readable.js:518:12)
    at ParserStream.EventEmitter.emit (events.js:95:17)
    at spreadArgs (/node_modules/fast-csv/lib/parser_stream.js:20:21)
</pre>

**Comment by NickDiMucci** [comment]
Hate to bring this back from the dead, but is there a way to catch this more elegantly or override the parsing behavior so I can manually handle this? At the very least I need to be able to just mark & discard these type of rows and continue the stream, but right now the stream ends due to the error event.

**Comment by empeje** [comment]
Hi there, I have the same issue with @NickDiMucci, is there any possibilities for another solution like what Nick has said?
