### ISSUE TITLE
Bug in writer

### ISSUE THREAD

**Issue by digitalblur** [C2FO/fast-csv#80]
Trying the example:
csv
    .fromPath("my.csv", {headers: true, objectMode: true})
    .pipe(csv.createWriteStream({headers: true}))
    .pipe(fs.createWriteStream("out.csv", {encoding: "utf8"}));

formatter.js line 88: headers = hash.keys(item);
is expecting an object but item is a string so the script crashes:

TypeError
    at Object.keys (/Users/tbentz/code/nodejs/extracts/extract_process/node_modules/fast-csv/node_modules/object-extended/index.js:116:23)
    at Readable.writer.write (/Users/tbentz/code/nodejs/extracts/extract_process/node_modules/fast-csv/lib/formatter.js:88:36)

**Comment by doug-martin** [comment]
Need more info in order to diagnose.
